services:
  deno:
    build:
      context: .devcontainer
      dockerfile: Dockerfile
    volumes:
      - ./workspace:/workspace
      - ./.devcontainer/entrypoint.sh:/entrypoint.sh
    environment:
      - UID=1000
      - UNAME=user
      - GID=1000
      - GNAME=user
    working_dir: /workspace
    entrypoint: /entrypoint.sh
    tty: true