services:
  deno:
    build:
      context: .devcontainer
      dockerfile: Dockerfile
    volumes:
      - ./workspace:/workspace
    working_dir: /workspace
    command:  "deno run -A ./src/main.ts"
